# Generated by Django 3.2 on 2025-08-27 18:42

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plot', models.TextField(blank=True, null=True)),
                ('genres', djongo.models.fields.JSONField(blank=True, null=True)),
                ('runtime', models.IntegerField(blank=True, null=True)),
                ('cast', djongo.models.fields.JSONField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('year', models.CharField(blank=True, max_length=4, null=True)),
                ('imdb', djongo.models.fields.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'movies',
            },
        ),
    ]
