# Generated by Django 3.2 on 2025-08-27 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mongo_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelicula',
            name='poster',
            field=models.TextField(blank=True, null=True),
        ),
    ]
