# Generated by Django 3.2 on 2025-08-27 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mongo_app', '0003_auto_20250827_1357'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pelicula',
            old_name='_id',
            new_name='id',
        ),
    ]
