# Generated by Django 3.2 on 2025-08-27 19:07

from django.db import migrations
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mongo_app', '0006_rename__id_pelicula_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelicula',
            name='awards',
            field=djongo.models.fields.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pelicula',
            name='countries',
            field=djongo.models.fields.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pelicula',
            name='directors',
            field=djongo.models.fields.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pelicula',
            name='languages',
            field=djongo.models.fields.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pelicula',
            name='writers',
            field=djongo.models.fields.JSONField(blank=True, null=True),
        ),
    ]
