# Generated by Django 3.2 on 2025-08-27 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mongo_app', '0007_auto_20250827_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelicula',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
