# Generated by Django 3.2 on 2025-08-27 19:16

from django.db import migrations
import django.utils.timezone
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mongo_app', '0008_alter_pelicula_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pelicula',
            name='id',
        ),
        migrations.AddField(
            model_name='pelicula',
            name='_id',
            field=djongo.models.fields.ObjectIdField(auto_created=True, default=django.utils.timezone.now, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
